#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1800_FileMerger_bin_Data;
		#define SEC_START_ADDR A1800_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1800_FileMerger_bin_start;
		extern uint32_t _binary_A1800_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1800_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000040)	//Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
#define _01KAIDENG_WAV                 0       	//File  Index:0           File  Name:01kaideng_wav.a18 
#define _01KAIDENG_WAV_ADDR            (SEC_START_ADDR + 0x000040)	//File  Addr :0x000040    File  Name:01kaideng_wav.a18 
#define _02GUANDENG_WAV                1       	//File  Index:1           File  Name:02guandeng_wav.a18 
#define _02GUANDENG_WAV_ADDR           (SEC_START_ADDR + 0x0004f6)	//File  Addr :0x0004f6    File  Name:02guandeng_wav.a18 
#define _03BAIFZS_WAV                  2       	//File  Index:2           File  Name:03baifzs_wav.a18 
#define _03BAIFZS_WAV_ADDR             (SEC_START_ADDR + 0x000772)	//File  Addr :0x000772    File  Name:03baifzs_wav.a18 
#define _04BAIFZWS_WAV                 3       	//File  Index:3           File  Name:04baifzws_wav.a18 
#define _04BAIFZWS_WAV_ADDR            (SEC_START_ADDR + 0x000c0a)	//File  Addr :0x000c0a    File  Name:04baifzws_wav.a18 
#define _05BAIFZB_WAV                  4       	//File  Index:4           File  Name:05baifzb_wav.a18 
#define _05BAIFZB_WAV_ADDR             (SEC_START_ADDR + 0x0011b0)	//File  Addr :0x0011b0    File  Name:05baifzb_wav.a18 
#define _06SHIFZ_WAV                   5       	//File  Index:5           File  Name:06shifz_wav.a18 
#define _06SHIFZ_WAV_ADDR              (SEC_START_ADDR + 0x0015b2)	//File  Addr :0x0015b2    File  Name:06shifz_wav.a18 
#define _07SANSHIFZ_WAV                6       	//File  Index:6           File  Name:07sanshifz_wav.a18 
#define _07SANSHIFZ_WAV_ADDR           (SEC_START_ADDR + 0x00191e)	//File  Addr :0x00191e    File  Name:07sanshifz_wav.a18 
#define _08DINGSQX_WAV                 7       	//File  Index:7           File  Name:08dingsqx_wav.a18 
#define _08DINGSQX_WAV_ADDR            (SEC_START_ADDR + 0x001d7a)	//File  Addr :0x001d7a    File  Name:08dingsqx_wav.a18 

#endif /* __FILE_MERGER_H__ */
