#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* MP3_FileMerger_bin_Data;
		#define SEC_START_ADDR MP3_FileMerger_bin_Data
	#else
		extern uint8_t _binary_MP3_FileMerger_bin_start;
		extern uint32_t _binary_MP3_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_MP3_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000040)	//Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
#define _1_KILLING_ME_SOFTLY           0       	//File  Index:0           File  Name:1_Killing Me Softly.mp3 
#define _1_KILLING_ME_SOFTLY_ADDR      (SEC_START_ADDR + 0x000040)	//File  Addr :0x000040    File  Name:1_Killing Me Softly.mp3 
#define _2_LET_S_START_FROM_HERE       1       	//File  Index:1           File  Name:2_Let's Start From Here.mp3 
#define _2_LET_S_START_FROM_HERE_ADDR  (SEC_START_ADDR + 0x0946ff)	//File  Addr :0x0946ff    File  Name:2_Let's Start From Here.mp3 
#define _3_CLOCK                       2       	//File  Index:2           File  Name:3_clock.mp3 
#define _3_CLOCK_ADDR                  (SEC_START_ADDR + 0x19656d)	//File  Addr :0x19656d    File  Name:3_clock.mp3 
#define _4_WORTHIT                     3       	//File  Index:3           File  Name:4_worthit.mp3 
#define _4_WORTHIT_ADDR                (SEC_START_ADDR + 0x308add)	//File  Addr :0x308add    File  Name:4_worthit.mp3 
#define _5_MERRYCHRISTMAS              4       	//File  Index:4           File  Name:5_MerryChristmas.mp3 
#define _5_MERRYCHRISTMAS_ADDR         (SEC_START_ADDR + 0x3780b3)	//File  Addr :0x3780b3    File  Name:5_MerryChristmas.mp3 
#define _6_PSEUDO                      5       	//File  Index:5           File  Name:6_Pseudo.mp3 
#define _6_PSEUDO_ADDR                 (SEC_START_ADDR + 0x427f65)	//File  Addr :0x427f65    File  Name:6_Pseudo.mp3 

#endif /* __FILE_MERGER_H__ */
