_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000040	;Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
_1_Killing_Me_Softly              .equ    0       	;File  Index:0           File  Name:1_Killing Me Softly.mp3 
_1_Killing_Me_Softly_Addr         .equ    0x000040	;File  Addr :0x000040    File  Name:1_Killing Me Softly.mp3 
_2_Let_s_Start_From_Here          .equ    1       	;File  Index:1           File  Name:2_Let's Start From Here.mp3 
_2_Let_s_Start_From_Here_Addr     .equ    0x0946ff	;File  Addr :0x0946ff    File  Name:2_Let's Start From Here.mp3 
_3_clock                          .equ    2       	;File  Index:2           File  Name:3_clock.mp3 
_3_clock_Addr                     .equ    0x19656d	;File  Addr :0x19656d    File  Name:3_clock.mp3 
_4_worthit                        .equ    3       	;File  Index:3           File  Name:4_worthit.mp3 
_4_worthit_Addr                   .equ    0x308add	;File  Addr :0x308add    File  Name:4_worthit.mp3 
_5_MerryChristmas                 .equ    4       	;File  Index:4           File  Name:5_MerryChristmas.mp3 
_5_MerryChristmas_Addr            .equ    0x3780b3	;File  Addr :0x3780b3    File  Name:5_MerryChristmas.mp3 
_6_Pseudo                         .equ    5       	;File  Index:5           File  Name:6_Pseudo.mp3 
_6_Pseudo_Addr                    .equ    0x427f65	;File  Addr :0x427f65    File  Name:6_Pseudo.mp3 
