_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000080	;Group Addr :0x000080    Group Name:Group_Table     Group Type:Unknown 
_disney1                          .equ    0       	;File  Index:0           File  Name:disney1.sp4 
_disney1_Addr                     .equ    0x000080	;File  Addr :0x000080    File  Name:disney1.sp4 
_happy                            .equ    1       	;File  Index:1           File  Name:happy.sp4 
_happy_Addr                       .equ    0x022fdb	;File  Addr :0x022fdb    File  Name:happy.sp4 
_tk2                              .equ    2       	;File  Index:2           File  Name:tk2.sp5 
_tk2_Addr                         .equ    0x0373cd	;File  Addr :0x0373cd    File  Name:tk2.sp5 
