#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* PCM_FileMerger_bin_Data;
		#define SEC_START_ADDR PCM_FileMerger_bin_Data
	#else
		extern uint8_t _binary_PCM_FileMerger_bin_start;
		extern uint32_t _binary_PCM_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_PCM_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000100)	//Group Addr :0x000100    Group Name:Group_Table     Group Type:Unknown 
#define _01B_WAV                       0       	//File  Index:0           File  Name:01b_wav.pcmgpce 
#define _01B_WAV_ADDR                  (SEC_START_ADDR + 0x000100)	//File  Addr :0x000100    File  Name:01b_wav.pcmgpce 
#define _01C_WAV                       1       	//File  Index:1           File  Name:01c_wav.pcmgpce 
#define _01C_WAV_ADDR                  (SEC_START_ADDR + 0x00fe44)	//File  Addr :0x00fe44    File  Name:01c_wav.pcmgpce 
#define _13_WAV                        2       	//File  Index:2           File  Name:13_wav.pcmgpce 
#define _13_WAV_ADDR                   (SEC_START_ADDR + 0x01c75e)	//File  Addr :0x01c75e    File  Name:13_wav.pcmgpce 
#define _ENG4B_WAV                     3       	//File  Index:3           File  Name:eng4b_wav.pcmgpce 
#define _ENG4B_WAV_ADDR                (SEC_START_ADDR + 0x041c36)	//File  Addr :0x041c36    File  Name:eng4b_wav.pcmgpce 
#define _ENG5B_WAV                     4       	//File  Index:4           File  Name:eng5b_wav.pcmgpce 
#define _ENG5B_WAV_ADDR                (SEC_START_ADDR + 0x05302a)	//File  Addr :0x05302a    File  Name:eng5b_wav.pcmgpce 
#define _ENG5_WAV                      5       	//File  Index:5           File  Name:eng5_wav.pcmgpce 
#define _ENG5_WAV_ADDR                 (SEC_START_ADDR + 0x0669b4)	//File  Addr :0x0669b4    File  Name:eng5_wav.pcmgpce 
#define _ENG7_WAV                      6       	//File  Index:6           File  Name:eng7_wav.pcmgpce 
#define _ENG7_WAV_ADDR                 (SEC_START_ADDR + 0x0861e2)	//File  Addr :0x0861e2    File  Name:eng7_wav.pcmgpce 
#define _ENGLISHSTORY1_WAV             7       	//File  Index:7           File  Name:englishstory1_wav.pcmgpce 
#define _ENGLISHSTORY1_WAV_ADDR        (SEC_START_ADDR + 0x09ac06)	//File  Addr :0x09ac06    File  Name:englishstory1_wav.pcmgpce 
#define _ENGLISHSTORYS_WAV             8       	//File  Index:8           File  Name:englishstorys_wav.pcmgpce 
#define _ENGLISHSTORYS_WAV_ADDR        (SEC_START_ADDR + 0x0b938a)	//File  Addr :0x0b938a    File  Name:englishstorys_wav.pcmgpce 
#define _TRACK03B_WAV                  9       	//File  Index:9           File  Name:track03b_wav.pcmgpce 
#define _TRACK03B_WAV_ADDR             (SEC_START_ADDR + 0x1024e0)	//File  Addr :0x1024e0    File  Name:track03b_wav.pcmgpce 
#define _TRACK18A_WAV                  10      	//File  Index:10          File  Name:track18a_wav.pcmgpce 
#define _TRACK18A_WAV_ADDR             (SEC_START_ADDR + 0x117664)	//File  Addr :0x117664    File  Name:track18a_wav.pcmgpce 

#endif /* __FILE_MERGER_H__ */
