_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000100	;Group Addr :0x000100    Group Name:Group_Table     Group Type:Unknown 
_01b_wav                          .equ    0       	;File  Index:0           File  Name:01b_wav.pcmgpce 
_01b_wav_Addr                     .equ    0x000100	;File  Addr :0x000100    File  Name:01b_wav.pcmgpce 
_01c_wav                          .equ    1       	;File  Index:1           File  Name:01c_wav.pcmgpce 
_01c_wav_Addr                     .equ    0x00fe44	;File  Addr :0x00fe44    File  Name:01c_wav.pcmgpce 
_13_wav                           .equ    2       	;File  Index:2           File  Name:13_wav.pcmgpce 
_13_wav_Addr                      .equ    0x01c75e	;File  Addr :0x01c75e    File  Name:13_wav.pcmgpce 
_eng4b_wav                        .equ    3       	;File  Index:3           File  Name:eng4b_wav.pcmgpce 
_eng4b_wav_Addr                   .equ    0x041c36	;File  Addr :0x041c36    File  Name:eng4b_wav.pcmgpce 
_eng5b_wav                        .equ    4       	;File  Index:4           File  Name:eng5b_wav.pcmgpce 
_eng5b_wav_Addr                   .equ    0x05302a	;File  Addr :0x05302a    File  Name:eng5b_wav.pcmgpce 
_eng5_wav                         .equ    5       	;File  Index:5           File  Name:eng5_wav.pcmgpce 
_eng5_wav_Addr                    .equ    0x0669b4	;File  Addr :0x0669b4    File  Name:eng5_wav.pcmgpce 
_eng7_wav                         .equ    6       	;File  Index:6           File  Name:eng7_wav.pcmgpce 
_eng7_wav_Addr                    .equ    0x0861e2	;File  Addr :0x0861e2    File  Name:eng7_wav.pcmgpce 
_englishstory1_wav                .equ    7       	;File  Index:7           File  Name:englishstory1_wav.pcmgpce 
_englishstory1_wav_Addr           .equ    0x09ac06	;File  Addr :0x09ac06    File  Name:englishstory1_wav.pcmgpce 
_englishstorys_wav                .equ    8       	;File  Index:8           File  Name:englishstorys_wav.pcmgpce 
_englishstorys_wav_Addr           .equ    0x0b938a	;File  Addr :0x0b938a    File  Name:englishstorys_wav.pcmgpce 
_track03b_wav                     .equ    9       	;File  Index:9           File  Name:track03b_wav.pcmgpce 
_track03b_wav_Addr                .equ    0x1024e0	;File  Addr :0x1024e0    File  Name:track03b_wav.pcmgpce 
_track18a_wav                     .equ    10      	;File  Index:10          File  Name:track18a_wav.pcmgpce 
_track18a_wav_Addr                .equ    0x117664	;File  Addr :0x117664    File  Name:track18a_wav.pcmgpce 
