_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000040	;Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
_toystory4                        .equ    0       	;File  Index:0           File  Name:toystory4.a18 
_toystory4_Addr                   .equ    0x000040	;File  Addr :0x000040    File  Name:toystory4.a18 
_speechless2                      .equ    1       	;File  Index:1           File  Name:speechless2.a18 
_speechless2_Addr                 .equ    0x00bdce	;File  Addr :0x00bdce    File  Name:speechless2.a18 
_hood                             .equ    2       	;File  Index:2           File  Name:hood.a18 
_hood_Addr                        .equ    0x013a34	;File  Addr :0x013a34    File  Name:hood.a18 
_hakunamatata                     .equ    3       	;File  Index:3           File  Name:hakunamatata.a18 
_hakunamatata_Addr                .equ    0x01bcb2	;File  Addr :0x01bcb2    File  Name:hakunamatata.a18 
_arobian                          .equ    4       	;File  Index:4           File  Name:arobian.a18 
_arobian_Addr                     .equ    0x028620	;File  Addr :0x028620    File  Name:arobian.a18 
