#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1801_FileMerger_bin_Data;
		#define SEC_START_ADDR A1801_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1801_FileMerger_bin_start;
		extern uint32_t _binary_A1801_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1801_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000040)	//Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
#define _TOYSTORY4                     0       	//File  Index:0           File  Name:toystory4.a18 
#define _TOYSTORY4_ADDR                (SEC_START_ADDR + 0x000040)	//File  Addr :0x000040    File  Name:toystory4.a18 
#define _SPEECHLESS2                   1       	//File  Index:1           File  Name:speechless2.a18 
#define _SPEECHLESS2_ADDR              (SEC_START_ADDR + 0x00bdce)	//File  Addr :0x00bdce    File  Name:speechless2.a18 
#define _HOOD                          2       	//File  Index:2           File  Name:hood.a18 
#define _HOOD_ADDR                     (SEC_START_ADDR + 0x013a34)	//File  Addr :0x013a34    File  Name:hood.a18 
#define _HAKUNAMATATA                  3       	//File  Index:3           File  Name:hakunamatata.a18 
#define _HAKUNAMATATA_ADDR             (SEC_START_ADDR + 0x01bcb2)	//File  Addr :0x01bcb2    File  Name:hakunamatata.a18 
#define _AROBIAN                       4       	//File  Index:4           File  Name:arobian.a18 
#define _AROBIAN_ADDR                  (SEC_START_ADDR + 0x028620)	//File  Addr :0x028620    File  Name:arobian.a18 

#endif /* __FILE_MERGER_H__ */
