_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000040	;Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
_01kaideng_wav                    .equ    0       	;File  Index:0           File  Name:01kaideng_wav.a18 
_01kaideng_wav_Addr               .equ    0x000040	;File  Addr :0x000040    File  Name:01kaideng_wav.a18 
_02guandeng_wav                   .equ    1       	;File  Index:1           File  Name:02guandeng_wav.a18 
_02guandeng_wav_Addr              .equ    0x0004f6	;File  Addr :0x0004f6    File  Name:02guandeng_wav.a18 
_03baifzs_wav                     .equ    2       	;File  Index:2           File  Name:03baifzs_wav.a18 
_03baifzs_wav_Addr                .equ    0x000772	;File  Addr :0x000772    File  Name:03baifzs_wav.a18 
_04baifzws_wav                    .equ    3       	;File  Index:3           File  Name:04baifzws_wav.a18 
_04baifzws_wav_Addr               .equ    0x000c0a	;File  Addr :0x000c0a    File  Name:04baifzws_wav.a18 
_05baifzb_wav                     .equ    4       	;File  Index:4           File  Name:05baifzb_wav.a18 
_05baifzb_wav_Addr                .equ    0x0011b0	;File  Addr :0x0011b0    File  Name:05baifzb_wav.a18 
_06shifz_wav                      .equ    5       	;File  Index:5           File  Name:06shifz_wav.a18 
_06shifz_wav_Addr                 .equ    0x0015b2	;File  Addr :0x0015b2    File  Name:06shifz_wav.a18 
_07sanshifz_wav                   .equ    6       	;File  Index:6           File  Name:07sanshifz_wav.a18 
_07sanshifz_wav_Addr              .equ    0x00191e	;File  Addr :0x00191e    File  Name:07sanshifz_wav.a18 
_08dingsqx_wav                    .equ    7       	;File  Index:7           File  Name:08dingsqx_wav.a18 
_08dingsqx_wav_Addr               .equ    0x001d7a	;File  Addr :0x001d7a    File  Name:08dingsqx_wav.a18 
