_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000040	;Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
_1_Hello_Alexa_wav                .equ    0       	;File  Index:0           File  Name:1_Hello Alexa_wav.a181 
_1_Hello_Alexa_wav_Addr           .equ    0x000040	;File  Addr :0x000040    File  Name:1_Hello Alexa_wav.a181 
_2_Power_On_TV_wav                .equ    1       	;File  Index:1           File  Name:2_Power On TV_wav.a181 
_2_Power_On_TV_wav_Addr           .equ    0x000956	;File  Addr :0x000956    File  Name:2_Power On TV_wav.a181 
_3_Happy_new_year_wav             .equ    2       	;File  Index:2           File  Name:3_Happy new year_wav.a181 
_3_Happy_new_year_wav_Addr        .equ    0x0012e4	;File  Addr :0x0012e4    File  Name:3_Happy new year_wav.a181 
_4_Introduce_yourself_wav         .equ    3       	;File  Index:3           File  Name:4_Introduce yourself_wav.a181 
_4_Introduce_yourself_wav_Addr    .equ    0x001b0a	;File  Addr :0x001b0a    File  Name:4_Introduce yourself_wav.a181 
_5_Merry_Christmas_wav            .equ    4       	;File  Index:4           File  Name:5_Merry Christmas_wav.a181 
_5_Merry_Christmas_wav_Addr       .equ    0x002588	;File  Addr :0x002588    File  Name:5_Merry Christmas_wav.a181 
_6_Show_me_the_location_wav       .equ    5       	;File  Index:5           File  Name:6_Show me the location_wav.a181 
_6_Show_me_the_location_wav_Addr    .equ    0x002fb6	;File  Addr :0x002fb6    File  Name:6_Show me the location_wav.a181 
_7_How_is_the_weather_wav         .equ    6       	;File  Index:6           File  Name:7_How is the weather_wav.a181 
_7_How_is_the_weather_wav_Addr    .equ    0x003a84	;File  Addr :0x003a84    File  Name:7_How is the weather_wav.a181 
_8_May_the_force_be_with_you_wav    .equ    7       	;File  Index:7           File  Name:8_May the force be with you_wav.a181 
_8_May_the_force_be_with_you_wav_Addr    .equ    0x0041e2	;File  Addr :0x0041e2    File  Name:8_May the force be with you_wav.a181 
