#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1801_FileMerger_bin_Data;
		#define SEC_START_ADDR A1801_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1801_FileMerger_bin_start;
		extern uint32_t _binary_A1801_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1801_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000040)	//Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
#define _1_HELLO_ALEXA_WAV             0       	//File  Index:0           File  Name:1_Hello Alexa_wav.a181 
#define _1_HELLO_ALEXA_WAV_ADDR        (SEC_START_ADDR + 0x000040)	//File  Addr :0x000040    File  Name:1_Hello Alexa_wav.a181 
#define _2_POWER_ON_TV_WAV             1       	//File  Index:1           File  Name:2_Power On TV_wav.a181 
#define _2_POWER_ON_TV_WAV_ADDR        (SEC_START_ADDR + 0x000956)	//File  Addr :0x000956    File  Name:2_Power On TV_wav.a181 
#define _3_HAPPY_NEW_YEAR_WAV          2       	//File  Index:2           File  Name:3_Happy new year_wav.a181 
#define _3_HAPPY_NEW_YEAR_WAV_ADDR     (SEC_START_ADDR + 0x0012e4)	//File  Addr :0x0012e4    File  Name:3_Happy new year_wav.a181 
#define _4_INTRODUCE_YOURSELF_WAV      3       	//File  Index:3           File  Name:4_Introduce yourself_wav.a181 
#define _4_INTRODUCE_YOURSELF_WAV_ADDR (SEC_START_ADDR + 0x001b0a)	//File  Addr :0x001b0a    File  Name:4_Introduce yourself_wav.a181 
#define _5_MERRY_CHRISTMAS_WAV         4       	//File  Index:4           File  Name:5_Merry Christmas_wav.a181 
#define _5_MERRY_CHRISTMAS_WAV_ADDR    (SEC_START_ADDR + 0x002588)	//File  Addr :0x002588    File  Name:5_Merry Christmas_wav.a181 
#define _6_SHOW_ME_THE_LOCATION_WAV    5       	//File  Index:5           File  Name:6_Show me the location_wav.a181 
#define _6_SHOW_ME_THE_LOCATION_WAV_ADDR (SEC_START_ADDR + 0x002fb6)	//File  Addr :0x002fb6    File  Name:6_Show me the location_wav.a181 
#define _7_HOW_IS_THE_WEATHER_WAV      6       	//File  Index:6           File  Name:7_How is the weather_wav.a181 
#define _7_HOW_IS_THE_WEATHER_WAV_ADDR (SEC_START_ADDR + 0x003a84)	//File  Addr :0x003a84    File  Name:7_How is the weather_wav.a181 
#define _8_MAY_THE_FORCE_BE_WITH_YOU_WAV 7       	//File  Index:7           File  Name:8_May the force be with you_wav.a181 
#define _8_MAY_THE_FORCE_BE_WITH_YOU_WAV_ADDR (SEC_START_ADDR + 0x0041e2)	//File  Addr :0x0041e2    File  Name:8_May the force be with you_wav.a181 

#endif /* __FILE_MERGER_H__ */
