#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1800_FileMerger_bin_Data;
		#define SEC_START_ADDR A1800_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1800_FileMerger_bin_start;
		extern uint32_t _binary_A1800_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1800_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000080)	//Group Addr :0x000080    Group Name:Group_Table     Group Type:Unknown 
#define _1                             0       	//File  Index:0           File  Name:1.a18 
#define _1_ADDR                        (SEC_START_ADDR + 0x000080)	//File  Addr :0x000080    File  Name:1.a18 
#define _2                             1       	//File  Index:1           File  Name:2.a18 
#define _2_ADDR                        (SEC_START_ADDR + 0x00046e)	//File  Addr :0x00046e    File  Name:2.a18 
#define _3                             2       	//File  Index:2           File  Name:3.a18 
#define _3_ADDR                        (SEC_START_ADDR + 0x0008fc)	//File  Addr :0x0008fc    File  Name:3.a18 
#define _4                             3       	//File  Index:3           File  Name:4.a18 
#define _4_ADDR                        (SEC_START_ADDR + 0x000d8a)	//File  Addr :0x000d8a    File  Name:4.a18 
#define _5                             4       	//File  Index:4           File  Name:5.a18 
#define _5_ADDR                        (SEC_START_ADDR + 0x001308)	//File  Addr :0x001308    File  Name:5.a18 
#define _6                             5       	//File  Index:5           File  Name:6.a18 
#define _6_ADDR                        (SEC_START_ADDR + 0x001836)	//File  Addr :0x001836    File  Name:6.a18 
#define _7                             6       	//File  Index:6           File  Name:7.a18 
#define _7_ADDR                        (SEC_START_ADDR + 0x001e04)	//File  Addr :0x001e04    File  Name:7.a18 
#define _8                             7       	//File  Index:7           File  Name:8.a18 
#define _8_ADDR                        (SEC_START_ADDR + 0x002332)	//File  Addr :0x002332    File  Name:8.a18 
#define _9                             8       	//File  Index:8           File  Name:9.a18 
#define _9_ADDR                        (SEC_START_ADDR + 0x002748)	//File  Addr :0x002748    File  Name:9.a18 
#define _10                            9       	//File  Index:9           File  Name:10.a18 
#define _10_ADDR                       (SEC_START_ADDR + 0x002bd6)	//File  Addr :0x002bd6    File  Name:10.a18 
#define _11                            10      	//File  Index:10          File  Name:11.a18 
#define _11_ADDR                       (SEC_START_ADDR + 0x002f9c)	//File  Addr :0x002f9c    File  Name:11.a18 
#define _12                            11      	//File  Index:11          File  Name:12.a18 
#define _12_ADDR                       (SEC_START_ADDR + 0x003452)	//File  Addr :0x003452    File  Name:12.a18 
#define _13                            12      	//File  Index:12          File  Name:13.a18 
#define _13_ADDR                       (SEC_START_ADDR + 0x003958)	//File  Addr :0x003958    File  Name:13.a18 
#define _14                            13      	//File  Index:13          File  Name:14.a18 
#define _14_ADDR                       (SEC_START_ADDR + 0x003fc6)	//File  Addr :0x003fc6    File  Name:14.a18 
#define _15                            14      	//File  Index:14          File  Name:15.a18 
#define _15_ADDR                       (SEC_START_ADDR + 0x004594)	//File  Addr :0x004594    File  Name:15.a18 
#define _16                            15      	//File  Index:15          File  Name:16.a18 
#define _16_ADDR                       (SEC_START_ADDR + 0x004b3a)	//File  Addr :0x004b3a    File  Name:16.a18 
#define _17                            16      	//File  Index:16          File  Name:17.a18 
#define _17_ADDR                       (SEC_START_ADDR + 0x005130)	//File  Addr :0x005130    File  Name:17.a18 
#define _18                            17      	//File  Index:17          File  Name:18.a18 
#define _18_ADDR                       (SEC_START_ADDR + 0x005776)	//File  Addr :0x005776    File  Name:18.a18 
#define _19                            18      	//File  Index:18          File  Name:19.a18 
#define _19_ADDR                       (SEC_START_ADDR + 0x005ca4)	//File  Addr :0x005ca4    File  Name:19.a18 
#define _20                            19      	//File  Index:19          File  Name:20.a18 
#define _20_ADDR                       (SEC_START_ADDR + 0x00624a)	//File  Addr :0x00624a    File  Name:20.a18 

#endif /* __FILE_MERGER_H__ */
