_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000080	;Group Addr :0x000080    Group Name:Group_Table     Group Type:Unknown 
_1                                .equ    0       	;File  Index:0           File  Name:1.a18 
_1_Addr                           .equ    0x000080	;File  Addr :0x000080    File  Name:1.a18 
_2                                .equ    1       	;File  Index:1           File  Name:2.a18 
_2_Addr                           .equ    0x00046e	;File  Addr :0x00046e    File  Name:2.a18 
_3                                .equ    2       	;File  Index:2           File  Name:3.a18 
_3_Addr                           .equ    0x0008fc	;File  Addr :0x0008fc    File  Name:3.a18 
_4                                .equ    3       	;File  Index:3           File  Name:4.a18 
_4_Addr                           .equ    0x000d8a	;File  Addr :0x000d8a    File  Name:4.a18 
_5                                .equ    4       	;File  Index:4           File  Name:5.a18 
_5_Addr                           .equ    0x001308	;File  Addr :0x001308    File  Name:5.a18 
_6                                .equ    5       	;File  Index:5           File  Name:6.a18 
_6_Addr                           .equ    0x001836	;File  Addr :0x001836    File  Name:6.a18 
_7                                .equ    6       	;File  Index:6           File  Name:7.a18 
_7_Addr                           .equ    0x001e04	;File  Addr :0x001e04    File  Name:7.a18 
_8                                .equ    7       	;File  Index:7           File  Name:8.a18 
_8_Addr                           .equ    0x002332	;File  Addr :0x002332    File  Name:8.a18 
_9                                .equ    8       	;File  Index:8           File  Name:9.a18 
_9_Addr                           .equ    0x002748	;File  Addr :0x002748    File  Name:9.a18 
_10                               .equ    9       	;File  Index:9           File  Name:10.a18 
_10_Addr                          .equ    0x002bd6	;File  Addr :0x002bd6    File  Name:10.a18 
_11                               .equ    10      	;File  Index:10          File  Name:11.a18 
_11_Addr                          .equ    0x002f9c	;File  Addr :0x002f9c    File  Name:11.a18 
_12                               .equ    11      	;File  Index:11          File  Name:12.a18 
_12_Addr                          .equ    0x003452	;File  Addr :0x003452    File  Name:12.a18 
_13                               .equ    12      	;File  Index:12          File  Name:13.a18 
_13_Addr                          .equ    0x003958	;File  Addr :0x003958    File  Name:13.a18 
_14                               .equ    13      	;File  Index:13          File  Name:14.a18 
_14_Addr                          .equ    0x003fc6	;File  Addr :0x003fc6    File  Name:14.a18 
_15                               .equ    14      	;File  Index:14          File  Name:15.a18 
_15_Addr                          .equ    0x004594	;File  Addr :0x004594    File  Name:15.a18 
_16                               .equ    15      	;File  Index:15          File  Name:16.a18 
_16_Addr                          .equ    0x004b3a	;File  Addr :0x004b3a    File  Name:16.a18 
_17                               .equ    16      	;File  Index:16          File  Name:17.a18 
_17_Addr                          .equ    0x005130	;File  Addr :0x005130    File  Name:17.a18 
_18                               .equ    17      	;File  Index:17          File  Name:18.a18 
_18_Addr                          .equ    0x005776	;File  Addr :0x005776    File  Name:18.a18 
_19                               .equ    18      	;File  Index:18          File  Name:19.a18 
_19_Addr                          .equ    0x005ca4	;File  Addr :0x005ca4    File  Name:19.a18 
_20                               .equ    19      	;File  Index:19          File  Name:20.a18 
_20_Addr                          .equ    0x00624a	;File  Addr :0x00624a    File  Name:20.a18 
