_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000010	;Group Addr :0x000010    Group Name:Group_Table     Group Type:Unknown 
_CSP16_WWE_pack                   .equ    0       	;File  Index:0           File  Name:CSP16_WWE_pack.bin 
_CSP16_WWE_pack_Addr              .equ    0x000010	;File  Addr :0x000010    File  Name:CSP16_WWE_pack.bin 
