#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1801_FileMerger_bin_Data;
		#define SEC_START_ADDR A1801_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1801_FileMerger_bin_start;
		extern uint32_t _binary_A1801_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1801_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000040)	//Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
#define _TRACK18A_WAV                  0       	//File  Index:0           File  Name:track18a_wav.a181 
#define _TRACK18A_WAV_ADDR             (SEC_START_ADDR + 0x000040)	//File  Addr :0x000040    File  Name:track18a_wav.a181 
#define _TRACK03B_WAV                  1       	//File  Index:1           File  Name:track03b_wav.a181 
#define _TRACK03B_WAV_ADDR             (SEC_START_ADDR + 0x00114e)	//File  Addr :0x00114e    File  Name:track03b_wav.a181 
#define _ENGLISHSTORYS_WAV             2       	//File  Index:2           File  Name:englishstorys_wav.a181 
#define _ENGLISHSTORYS_WAV_ADDR        (SEC_START_ADDR + 0x0027fc)	//File  Addr :0x0027fc    File  Name:englishstorys_wav.a181 
#define _ENGLISHSTORY1_WAV             3       	//File  Index:3           File  Name:englishstory1_wav.a181 
#define _ENGLISHSTORY1_WAV_ADDR        (SEC_START_ADDR + 0x00737a)	//File  Addr :0x00737a    File  Name:englishstory1_wav.a181 
#define _ENG7_WAV                      4       	//File  Index:4           File  Name:eng7_wav.a181 
#define _ENG7_WAV_ADDR                 (SEC_START_ADDR + 0x009450)	//File  Addr :0x009450    File  Name:eng7_wav.a181 
#define _ENG5_WAV                      5       	//File  Index:5           File  Name:eng5_wav.a181 
#define _ENG5_WAV_ADDR                 (SEC_START_ADDR + 0x00ab76)	//File  Addr :0x00ab76    File  Name:eng5_wav.a181 
#define _ENG5B_WAV                     6       	//File  Index:6           File  Name:eng5b_wav.a181 
#define _ENG5B_WAV_ADDR                (SEC_START_ADDR + 0x00cd64)	//File  Addr :0x00cd64    File  Name:eng5b_wav.a181 
#define _ENG4B_WAV                     7       	//File  Index:7           File  Name:eng4b_wav.a181 
#define _ENG4B_WAV_ADDR                (SEC_START_ADDR + 0x00e372)	//File  Addr :0x00e372    File  Name:eng4b_wav.a181 
#define _13_WAV                        8       	//File  Index:8           File  Name:13_wav.a181 
#define _13_WAV_ADDR                   (SEC_START_ADDR + 0x00f728)	//File  Addr :0x00f728    File  Name:13_wav.a181 
#define _01C_WAV                       9       	//File  Index:9           File  Name:01c_wav.a181 
#define _01C_WAV_ADDR                  (SEC_START_ADDR + 0x011ede)	//File  Addr :0x011ede    File  Name:01c_wav.a181 
#define _01B_WAV                       10      	//File  Index:10          File  Name:01b_wav.a181 
#define _01B_WAV_ADDR                  (SEC_START_ADDR + 0x012de4)	//File  Addr :0x012de4    File  Name:01b_wav.a181 

#endif /* __FILE_MERGER_H__ */
