_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000040	;Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
_track18a_wav                     .equ    0       	;File  Index:0           File  Name:track18a_wav.a181 
_track18a_wav_Addr                .equ    0x000040	;File  Addr :0x000040    File  Name:track18a_wav.a181 
_track03b_wav                     .equ    1       	;File  Index:1           File  Name:track03b_wav.a181 
_track03b_wav_Addr                .equ    0x00114e	;File  Addr :0x00114e    File  Name:track03b_wav.a181 
_englishstorys_wav                .equ    2       	;File  Index:2           File  Name:englishstorys_wav.a181 
_englishstorys_wav_Addr           .equ    0x0027fc	;File  Addr :0x0027fc    File  Name:englishstorys_wav.a181 
_englishstory1_wav                .equ    3       	;File  Index:3           File  Name:englishstory1_wav.a181 
_englishstory1_wav_Addr           .equ    0x00737a	;File  Addr :0x00737a    File  Name:englishstory1_wav.a181 
_eng7_wav                         .equ    4       	;File  Index:4           File  Name:eng7_wav.a181 
_eng7_wav_Addr                    .equ    0x009450	;File  Addr :0x009450    File  Name:eng7_wav.a181 
_eng5_wav                         .equ    5       	;File  Index:5           File  Name:eng5_wav.a181 
_eng5_wav_Addr                    .equ    0x00ab76	;File  Addr :0x00ab76    File  Name:eng5_wav.a181 
_eng5b_wav                        .equ    6       	;File  Index:6           File  Name:eng5b_wav.a181 
_eng5b_wav_Addr                   .equ    0x00cd64	;File  Addr :0x00cd64    File  Name:eng5b_wav.a181 
_eng4b_wav                        .equ    7       	;File  Index:7           File  Name:eng4b_wav.a181 
_eng4b_wav_Addr                   .equ    0x00e372	;File  Addr :0x00e372    File  Name:eng4b_wav.a181 
_13_wav                           .equ    8       	;File  Index:8           File  Name:13_wav.a181 
_13_wav_Addr                      .equ    0x00f728	;File  Addr :0x00f728    File  Name:13_wav.a181 
_01c_wav                          .equ    9       	;File  Index:9           File  Name:01c_wav.a181 
_01c_wav_Addr                     .equ    0x011ede	;File  Addr :0x011ede    File  Name:01c_wav.a181 
_01b_wav                          .equ    10      	;File  Index:10          File  Name:01b_wav.a181 
_01b_wav_Addr                     .equ    0x012de4	;File  Addr :0x012de4    File  Name:01b_wav.a181 
